name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  id-token: write
  pages: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    # Deploy to the github-pages environment
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4' # Not needed with a .ruby-version, .tool-versions or mise.toml
      - run: gem install yard
      - name: Build
        run: bash ./scripts/build-docs.sh
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./yard-docs
          destination_dir: tags/${{ github.ref_name }}
          keep_files: true  # This preserves existing files

  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set env vars"
        run: |
          TAG_NAME=${{ github.ref_name }}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "SUBJECT='Release for $TAG_NAME'"
      - name: "Create latest release"
        if: github.ref_name == 'main'
        run: |
          gh release delete development --yes || true
          git push origin development || true
          gh release create development --title "$SUBJECT" --generate-notes --target $GITHUB_SHA ./mygame/lib/*
      - name: "Create Tag Release"
        if: github.ref_name != 'main'
        run: |
          gh release create $TAG_NAME --title "$SUBJECT" --generate-notes --target $GITHUB_SHA ./mygame/lib/*
